### ISSUE TITLE
Google Bots Unable to Crawl Homepage 

### ISSUE THREAD

**Issue by innovativedmm** [politicalrev/political-revolution.com#35]
- Robot.txt is preventing google from crawling the homepage.
- Hiding the 4 .js files in headers is preventing Google from crawling the site.
- Google crawl cannot currently access the website's homepage.

**Comment by Smona** [comment]
This should be fixed by the removal of a robots meta tag in https://github.com/politicalrev/political-revolution.com/commit/2bb0193a3153f2bb06be2a0e8767e0f1e99e651d#diff-88dbf5b897f4dfd277916a9d3ec36127L16

@innovativedmm which files do you refer to being hidden? And how is that affecting Google's ability to index us?

**Comment by innovativedmm** [comment]
Fixed now. I'll be more detailed writing issues. My apologies.

**Comment by Smona** [comment]
I'm already seeing improvement! <3
